version: '3.8'

services:
  fraud-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-api
    ports:
      - "5000:5000"
    networks:
      - monitoring
    volumes:
      - ./models:/app/models
      - ./app:/app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
